version: "3.7"

services:
  samba:
    image: dperson/samba
    container_name: samba
    environment:
      TZ: America/Argentina/Buenos_Aires
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /mnt/ssd/smb:/media
    command: '-u "pi;password" -s "smb;/media;yes;no"' # USB Hub should have access to anyone for anything
    # command: '-s "usbhub;/mnt" -s "Bobs Volume;/mnt2;yes;no;no;bob" -u "bob;bobspasswd"'

networks:
  default:
