services:
  samba:
    image: dperson/samba
    container_name: samba
    environment:
      USERID: "1000"
      GROUPID: "1000"
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    restart: unless-stopped
    volumes:
      - "${SHARE_DIR}:/media"
    command: '-g "vfs objects = recycle" -u "${SAMBA_USER};${SAMBA_PASSWORD}" -s "Compartido;/media;yes;no;no;${SAMBA_USER}"'
